name: Continuous Persistent VPS

on:
  schedule:
    - cron: '0 */5 * * *'  # Every 5 hours (GitHub cron can't do 5h30m exactly, see note below)
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 330  # 5h30m

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set hostname to DarkNodes
        run: sudo hostnamectl set-hostname DarkNodes

      - name: Download VPS backup (if any)
        uses: actions/download-artifact@v4
        with:
          name: vps-backup
          path: ./backup
        continue-on-error: true

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch

      - name: Install Tailscale official script
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Restore backup files
        run: |
          if [ -f ./backup/backup.zip ]; then
            unzip -o ./backup/backup.zip -d /
          else
            echo "No backup found, starting fresh"
          fi

      - name: Restore Tailscale state
        run: |
          if [ -f /opt/vps-backup/data/tailscaled.state ]; then
            sudo mkdir -p /var/lib/tailscale
            sudo cp /opt/vps-backup/data/tailscaled.state /var/lib/tailscale/tailscaled.state
            sudo chmod 600 /var/lib/tailscale/tailscaled.state
          fi

      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 8
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=DarkNodes || echo "Tailscale already up"

      - name: Create user Darknodes with sudo
        run: |
          if ! id -u Darknodes >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash Darknodes
            echo "Darknodes:Darknodes" | sudo chpasswd
            sudo usermod -aG sudo Darknodes
            echo "Darknodes ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/Darknodes
          fi

      - name: Change shell prompt to show DarkNodes
        run: |
          echo 'export PS1="\u@\h:\w\$ "' >> /home/Darknodes/.bashrc

      - name: Start tmate session for SSH access
        uses: mxschmitt/action-tmate@v3
        with:
          shell: /bin/bash

      - name: Show Tailscale IP and tmate info
        run: |
          echo "🔗 Tailscale IP:"
          tailscale ip -4 || echo "Tailscale IP not found"
          echo ""
          echo "💻 tmate SSH session:"
          cat $HOME/.tmate.sock/ssh

      - name: Sleep to keep VPS alive
        run: sleep 19800  # 5h30m

      - name: Backup VPS data and tailscale state
        run: |
          sudo mkdir -p /opt/vps-backup/data
          sudo cp /var/lib/tailscale/tailscaled.state /opt/vps-backup/data/
          sudo chown -R $USER:$USER /opt/vps-backup
          zip -r backup.zip /opt/vps-backup

      - name: Upload VPS backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: vps-backup
          path: backup.zip
